apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fzau2k15o-python 
  janus-idp.io/tekton: fzau2k15o-python
  backstage.io/kubernetes-id: fzau2k15o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fzau2k15o-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml