apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fzau2k15o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fzau2k15o-python 
  name: fzau2k15o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fzau2k15o-python 
